version: "4.11.1"
services:
  linebot:
    build: ./linebot
    ports:
      - "5000:5000"
    environment:
      - LINE_CHANNEL_SECRET=
      - LINE_ACCESS_TOKEN=
      - LINE_ADMIN_ID=
      - NGROK_TOKEN=2XDGm4WudGxz9ByHhiWIn6Pere9_4SpPSoBTgVxkeFsN1mSu2
      - WEBHOOK_PORT=80
      - API_PORT=8000
      - MONGO_HOST=linebot-iot-mongodb-1:27017/
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    depends_on:
      - "iot"
  iot:
    build: ./iot
    ports:
      - "8000:8000"
    environment:
      - MONGO_HOST=linebot-iot-mongodb-1:27017/
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    depends_on:
      - "mongodb"
  frontend:
    build: ./liff
    ports:
      - "6000:6000"
    environment:
      - MONGO_HOST=linebot-iot-mongodb-1:27017/
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    depends_on:
      - "mongodb"      
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    expose:
      - 27017