version: "4.11.1"
services:
  linebot:
    build: ./linebot
    ports:
      - "80:80"
    environment:
      - WEBHOOK_PORT=80
      - API_PORT=8000
      - LINE_CHANNEL_SECRET=ba8951fbfeae63ca76b2ac5ba035a917
      - LINE_ACCESS_TOKEN=qNziII5hVLmHW6yMlVyYj/QKxdWx7bjtrGxeBT4hwNVx40WUyYRgTz4nxVj6X0i+MYBOqDvhQYsBiC8zUWvNOmuRUPO1r04SdPYelZtioylC1kgZMFmOgXvLx68bW9LcuOSvrFYcZkPyf+/T/lTn/gdB04t89/1O/w1cDnyilFU=
      - LINE_ADMIN_ID=U6bfb9784dfa177ab5452161212deabcf
      - NGROK_TOKEN=2XR5dbPWJUnf0JWJa8CGILJ2HtC_76y5kVbQNpJiaqoHyznP2
    env_file: .env
    depends_on:
      - "iot"
  iot:
    build: ./iot
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - "mongodb"
  frontend:
    build: ./liff
    ports:
      - "6000:6000"
    env_file: .env
    depends_on:
      - "mongodb"
        
  mongodb:
    container_name: "mongodb"
    image: mongo
    ports:
      - "27017:27017"
    env_file: .env
    expose:
      - 27017